name             'appcanary'
maintainer       'Justin Alan Ryan'
maintainer_email 'bitmonk@icloud.com'
license          'Apache 2.0'
description      'Installs/Configures appcanary'
long_description 'Installs/Configures appcanary'
version          '0.1.4'
source_url       'https://github.com/bitmonk/chef-appcanary'

depends 'apt'
depends 'yum'
